Set lastResourceOptimisationInterfaceClassName on JTAEnvironmentBean for better integration with agroal
snowdrop/narayana-spring-boot pull request #107
Opened 2023-08-02 19:21 UTC by graben

Enhancement based on feedback from agroal/agroal#69. Implementation analog to WildFly [JTAEnvironmentBeanService.java#L61](https://github.com/wildfly/wildfly/blob/29.0.0.Final/transactions/src/main/java/org/jboss/as/txn/service/JTAEnvironmentBeanService.java#L61)

2023-08-04 21:33 UTC, barreiro requested changes

2023-08-04 21:33 UTC, barreiro commented on narayana-spring-boot-core/src/main/java/me/snowdrop/boot/narayana/core/properties/NarayanaPropertiesInitializer.java
> +        getPopulator(JTAEnvironmentBean.class).setPerformImmediateCleanupOfCommitMarkableResourceBranches(true);
Agroal will not support this. See [AG-214](https://issues.redhat.com/projects/AG/issues/AG-214) for further details. I also don't see an advantage on immediate cleanup, the recovery manager can do it in batch which ends up being more efficient.

2023-08-04 21:33 UTC, barreiro commented on narayana-spring-boot-core/src/main/java/me/snowdrop/boot/narayana/core/properties/NarayanaPropertiesInitializer.java
> +        getPopulator(JTAEnvironmentBean.class).setLastResourceOptimisationInterfaceClassName(lastResourceOptimisationInterface);
:+1:

2023-08-14 12:06 UTC, graben commented
@Sgitario : Could you plz review and merge

2023-08-14 12:10 UTC, Sgitario commented
@barreiro can you have a final review on this pull request? Thanks!

2023-08-15 12:58 UTC, graben commented
@Sgitario : Ready to merge and probably do a first release of 3.0?

2023-08-16 05:25 UTC, merged

2023-08-16 05:26 UTC, Sgitario commented
Merged.
About releasing, cc @jacobdotcosta

2023-08-17 13:14 UTC, graben commented
@Sgitario : Well, last time @jacobdotcosta was asked for a release, nothing happens. Anyone else able to do releases?

2023-08-17 13:56 UTC, Sgitario commented
> @Sgitario : Well, last time @jacobdotcosta was asked for a release, nothing happens. Anyone else able to do releases?

No that I'm aware of. @jacobdotcosta is on PTO until 28 Aug.